databases:
  - name: soko1
    databaseName: postgresql
    user: soko1

services:
  - type: web
    name: soko1
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soko1
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false